info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  app-config-list:
  - gkadmin
  - gk
server:
  port: 8989

management:
  port: 8990

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: https://eurekaregisterserver.herokuapp.com/eureka/